[package]
authors = ["Jørgen Nordmoen <jorgen.nordmoen@gmail.com>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "A platform agnostic driver to interface the HC-SR04 (ultrasonic distance sensor)"
documentation = "https://docs.rs/hc-sr04"
keywords = ["embedded-hal-driver", "ultrasonic distance", "sensor"]
license = "MIT OR Apache-2.0"
name = "hc-sr04"
repository = "https://github.com/nordmoen/hc-sr04"
version = "0.1.0"

[dependencies]
embedded-hal = "0.1.2"
nb = "0.1.1"
stm32f30x-hal = "0.1.2"
